spring:
  rabbitmq:
    host: 192.168.174.130
    port: 5672
    username: rabbitmq
    password: ych123
    virtual-host: /
    publisher-confirm-type: correlated
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual #手动签收
        prefetch: 1

